spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: jdbc:postgresql://localhost:5432/gdgoc
    username: postgres
    password:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          time_zone: Asia/Seoul

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${GOOGLE_REDIRECT_URI}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibername.type: trace

jwt:
  googleIssuer: ${GOOGLE_ISSUER}
  selfIssuer: ${SELF_ISSUER}
  secretKey: ${SECRET_KEY}