spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gdgoc
    username: postgres
    password:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibername.type: trace