spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gdgoc
    username: postgres
    password:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
    org.hibername.type: trace
