server:
  forward-headers-strategy: framework

spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: jdbc:postgresql://localhost:5432/gdgoc
    username: postgres
    password:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          time_zone: Asia/Seoul
  flyway:
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${GOOGLE_REDIRECT_URI}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibername.type: trace

jwt:
  googleIssuer: ${GOOGLE_ISSUER}
  selfIssuer: ${SELF_ISSUER}
  secretKey: ${SECRET_KEY}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_TEST_RESOURCE_BUCKET}
