version: "3.8"

services:
  app:
    image: "${DOCKER_HUB_USERNAME}/gdgoc-be-app-dev:latest"
    container_name: gdgoc-be-app-dev
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME_DEV}"
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - /home/ubuntu/gdgoc-be-app-dev/.env:/app/.env
    env_file:
      - .env
