version: "3.8"

services:
  app:
    image: "${DOCKER_HUB_USERNAME}/gdgoc-be-app:latest"
    container_name: gdgoc-be-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - /home/ubuntu/gdgoc-be-app/.env:/app/.env
    env_file:
      - .env

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v5.4.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    environment:
      DOZZLE_USERNAME: "${DOZZLE_USERNAME}"
      DOZZLE_PASSWORD: "${DOZZLE_PASSWORD}"
    restart: always
    env_file:
      - .env